
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ConverterWS", targetNamespace = "http://example.org/", wsdlLocation = "http://localhost:5252/?WSDL")
public class ConverterWS
    extends Service
{

    private static final URL CONVERTERWS_WSDL_LOCATION;
    private static final WebServiceException CONVERTERWS_EXCEPTION;
    private static final QName CONVERTERWS_QNAME = new QName("http://example.org/", "ConverterWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5252/?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONVERTERWS_WSDL_LOCATION = url;
        CONVERTERWS_EXCEPTION = e;
    }

    public ConverterWS() {
        super(__getWsdlLocation(), CONVERTERWS_QNAME);
    }

    public ConverterWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONVERTERWS_QNAME, features);
    }

    public ConverterWS(URL wsdlLocation) {
        super(wsdlLocation, CONVERTERWS_QNAME);
    }

    public ConverterWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONVERTERWS_QNAME, features);
    }

    public ConverterWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConverterWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Converter
     */
    @WebEndpoint(name = "ConverterPort")
    public Converter getConverterPort() {
        return super.getPort(new QName("http://example.org/", "ConverterPort"), Converter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Converter
     */
    @WebEndpoint(name = "ConverterPort")
    public Converter getConverterPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.org/", "ConverterPort"), Converter.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONVERTERWS_EXCEPTION!= null) {
            throw CONVERTERWS_EXCEPTION;
        }
        return CONVERTERWS_WSDL_LOCATION;
    }

}
